"""Decision-governance tooling (reusable template; determinism-first).

Owns the *mechanical* half of the decision workflow so the human/model only does the semantic
edits. stdlib only (Python 3.11+). Run from the project root with any Python 3.11+.

  new      — scaffold a decision: append the next D# row + GLANCE line, print propagation targets.
  sync     — regenerate the "at a glance" line/count (GLANCE) AND the INDEX doc/code tables
             (docs_manifest.txt) into their marker blocks.
  check    — coherence audit: sequential/unique IDs, GLANCE↔register match, dangling cites
             (a D# in docs but not in the register) and un-propagated decisions.
  coverage — verify each decision's *declared* targets literally cite it (lint-style, baselined).
  docs     — render only the INDEX tables from docs_manifest.txt (also run by sync).
  list/next— browse decisions / print the next free id.
  scope    — resolve a working set (decisions + docs in play) from a selector; the low-token context
             feed for the design->build->test loop. `--pin` saves it to agent/working_set.md.
  stats    — append governance signals to governance_metrics.csv + print the trend (autotracking).
  propagate— script cited-stub edits into a decision's declared targets that miss the cite; --apply writes.
  tune     — rank signal->knob actions from metrics + state; --apply runs the safe mechanical ones.
  audit    — periodic high-effort whole-tree pass: coherence + coverage debt + goal-alignment (D#<->O#)
             + drift/conformance (per-decision hash), as one ranked worklist; --apply / --update-hashes.

Conventions this tool assumes (see README/METHODOLOGY): a canonical register at
design/DECISIONS.md (with a GLANCE block), a master design/INDEX.md and agent/project.md carrying
GLANCE marker blocks, design/docs_manifest.txt driving the INDEX tables, and D# citations in docs.
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DECISIONS = ROOT / "design" / "DECISIONS.md"
PROJECT_MD = ROOT / "agent" / "project.md"                 # carries the GLANCE block + the ## Goals (O#) section
SYNC_TARGETS = [ROOT / "design" / "INDEX.md", PROJECT_MD]
SCAN_DIRS = [ROOT / "design", ROOT / "agent"]
WORKING_SET = ROOT / "agent" / "working_set.md"      # pinned session scope (scope --pin); excluded from cite scan
OPEN_DESIGN = ROOT / "design" / "OPEN_DESIGN.md"
METRICS_CSV = ROOT / "governance_metrics.csv"        # autotracking dataset (stats); excluded from init copy
# Root-level rationale/governance docs — surfaced by `scope` (the "why" tier) but NOT in SCAN_DIRS,
# so check/coverage/stats keep their existing design/+agent/ scope unchanged.
ROOT_DOCS = [ROOT / n for n in ("PRINCIPLES.md", "METHODOLOGY.md", "README.md", "ROADMAP.md")]

GLANCE_RE = re.compile(r"<!--\s*GLANCE\s*(.*?)-->", re.S)
GLANCE_LINE_RE = re.compile(r"^\s*D(\d+)\s*=\s*(.+?)\s*$")
ROW_ID_RE = re.compile(r"^\|\s*D(\d+)\s*\|")
MARK_START = "<!-- DECISIONS:GLANCE start (generated by scripts/decision_tools.py sync) -->"
MARK_END = "<!-- DECISIONS:GLANCE end -->"
CITE_RE = re.compile(r"\bD(\d+)\b")
GOAL_ID_RE = re.compile(r"\bO(\d+)\b")   # project-goal/objective id (## Goals in project.md) — alignment (D9)
PLACEHOLDER_RE = re.compile(r"^<.*>$")   # an un-filled template stub like "<rationale doc>"
DECISION_HASHES = ROOT / "scripts" / ".decision_hashes"   # D8/D9 conformance baseline (audit; excluded from init copy)


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def _has_rationale(cell: str) -> bool:
    """A decision's rationale cell carries a real 'why', not an empty/placeholder stub (DR check)."""
    c = cell.strip()
    return bool(c) and not PLACEHOLDER_RE.match(c)


def parse_glance() -> list[tuple[int, str]]:
    m = GLANCE_RE.search(_read(DECISIONS))
    if not m:
        return []
    out = []
    for line in m.group(1).splitlines():
        lm = GLANCE_LINE_RE.match(line)
        if lm:
            out.append((int(lm.group(1)), lm.group(2)))
    return out


def parse_sections() -> tuple[set[int], set[int]]:
    """Return (active_ids, superseded_ids) from the two register sections."""
    text = _read(DECISIONS)
    active, superseded = set(), set()
    bucket = None
    for line in text.splitlines():
        low = line.lower()
        if low.startswith("## active decisions"):
            bucket = active
            continue
        if low.startswith("## superseded"):
            bucket = superseded
            continue
        if low.startswith("## "):
            bucket = None
            continue
        m = ROW_ID_RE.match(line)
        if m and bucket is not None:
            bucket.add(int(m.group(1)))
    return active, superseded


def parse_rows() -> dict[int, dict]:
    """Active-section rows -> {id: {date, cat, statement, rationale, targets}} (for scope/stats)."""
    out, bucket = {}, False
    for line in _read(DECISIONS).splitlines():
        low = line.lower()
        if low.startswith("## active decisions"): bucket = True; continue
        if low.startswith("## ") and bucket: break
        m = ROW_ID_RE.match(line)
        if m and bucket:
            cells = [c.strip() for c in line.split("|")]   # ['', 'D#', date, cat, decision, rationale, targets, '']
            g = lambda i: cells[i] if -len(cells) <= i < len(cells) else ""
            out[int(m.group(1))] = {"date": g(2), "cat": g(3), "statement": g(4),
                                    "rationale": g(-3), "targets": g(-2)}
    return out


def scan_citations() -> dict[int, list[str]]:
    """Map D# -> list of doc paths (relative) citing it, excluding DECISIONS.md."""
    cites: dict[int, set[str]] = {}
    for d in SCAN_DIRS:
        for p in d.rglob("*.md"):
            if p.resolve() in (DECISIONS.resolve(), WORKING_SET.resolve()):
                continue
            rel = str(p.relative_to(ROOT)).replace("\\", "/")
            for n in {int(x) for x in CITE_RE.findall(_read(p))}:
                cites.setdefault(n, set()).add(rel)
    return {k: sorted(v) for k, v in cites.items()}


def build_glance_line(glance: list[tuple[int, str]]) -> str:
    ids = [i for i, _ in glance]
    rng = f"D{min(ids)}–D{max(ids)}" if ids else "none"
    items = " · ".join(f"D{i} {label}" for i, label in glance)
    return f"**{rng} active ({len(ids)}).** {items}."


def cmd_sync() -> int:
    glance = parse_glance()
    if not glance:
        print("! no GLANCE block found in DECISIONS.md"); return 1
    line = build_glance_line(glance)
    block = f"{MARK_START}\n{line}\n{MARK_END}"
    changed = []
    for t in SYNC_TARGETS:
        txt = _read(t)
        if MARK_START not in txt or MARK_END not in txt:
            print(f"! markers missing in {t.relative_to(ROOT)} — add them once, then re-run sync")
            continue
        new = re.sub(re.escape(MARK_START) + r".*?" + re.escape(MARK_END), block, txt, flags=re.S)
        if new != txt:
            t.write_text(new, encoding="utf-8"); changed.append(str(t.relative_to(ROOT)))
    print(f"synced glance ({len(glance)} decisions) -> {changed or 'no changes'}")
    render_docs()
    return 0


# --- INDEX tables generated from design/docs_manifest.txt (D24) ----------------
DOCS_MANIFEST = ROOT / "design" / "docs_manifest.txt"
INDEX = ROOT / "design" / "INDEX.md"
SECTION_RE = re.compile(r"^#\s+(\w+)\s*::\s*(.+)$")   # name = single word, so comments don't collide


def parse_manifest() -> list[dict]:
    sections, cur = [], None
    for raw in _read(DOCS_MANIFEST).splitlines():
        m = SECTION_RE.match(raw)
        if m:
            cur = {"name": m.group(1).strip(),
                   "cols": [c.strip() for c in m.group(2).split("|")], "rows": []}
            sections.append(cur)
        elif raw.strip() and not raw.lstrip().startswith("#") and cur is not None:
            cur["rows"].append(raw.strip())
    return sections


def _warn_orphans() -> None:
    man = _read(DOCS_MANIFEST)
    skip = {"INDEX.md", "DECISIONS.md", "ROUTINE_add_decision.md", "OPEN_DESIGN.md"}
    cand = (list((ROOT / "design").glob("*.md")) + list((ROOT / "design" / "build").glob("*.md"))
            + list((ROOT / "design" / "adventures").glob("*.md")))
    missing = [p.name for p in cand if p.name not in skip and p.name not in man]
    if missing:
        print("! docs on disk but not in manifest/INDEX:", ", ".join(sorted(missing)))
    for sec in parse_manifest():            # only real rows, not commented examples
        for r in sec["rows"]:
            for href in re.findall(r"\(([^)]+\.md)\)", r):
                if not (ROOT / "design" / href).exists():
                    print("! manifest href missing on disk:", href)


def render_docs(write: bool = True) -> int:
    text = _read(INDEX)
    for sec in parse_manifest():
        head = "| " + " | ".join(sec["cols"]) + " |\n|" + "|".join(["---"] * len(sec["cols"])) + "|"
        rows = "\n".join("| " + r + " |" for r in sec["rows"])
        start = f"<!-- DOCS:{sec['name']} start (generated by decision_tools.py sync) -->"
        block = f"{start}\n{head}\n{rows}\n<!-- DOCS:{sec['name']} end -->"
        pat = re.compile(re.escape(f"<!-- DOCS:{sec['name']} start") + r".*?"
                         + re.escape(f"<!-- DOCS:{sec['name']} end -->"), re.S)
        if pat.search(text):
            text = pat.sub(lambda _m: block, text)
        else:
            print(f"! INDEX marker for DOCS:{sec['name']} missing — add it once")
    if write:
        INDEX.write_text(text, encoding="utf-8")
    _warn_orphans()
    print("rendered INDEX tables from manifest")
    return 0


def cmd_docs() -> int:
    return render_docs()


def _coherence_issues() -> tuple[list[str], dict]:
    """Compute the coherence-audit issue list + a small context dict (active/superseded/cites).
    Shared by `check` (prints) and `audit` (folds into the worklist) so the rules live in one place."""
    active, superseded = parse_sections()
    glance = dict(parse_glance())
    cites = scan_citations()
    all_ids = active | superseded
    issues = []

    # sequential & unique
    if all_ids:
        expected = set(range(1, max(all_ids) + 1))
        missing = sorted(expected - all_ids)
        if missing:
            issues.append(f"gaps in IDs: {missing}")
    dup = active & superseded
    if dup:
        issues.append(f"IDs in both active & superseded: {sorted(dup)}")

    # glance vs active
    if set(glance) != active:
        only_g = sorted(set(glance) - active)
        only_a = sorted(active - set(glance))
        if only_g:
            issues.append(f"GLANCE has non-active IDs: {only_g}")
        if only_a:
            issues.append(f"active decisions missing from GLANCE: {only_a}")

    # dangling cites (referenced but undefined) & un-propagated (defined but uncited outside register)
    dangling = sorted(set(cites) - all_ids)
    if dangling:
        issues.append(f"cited but NOT in register (typos/dangling): {['D%d'%d for d in dangling]}")
    unprop = sorted(i for i in active if i not in cites)
    if unprop:
        issues.append(f"active but cited nowhere outside register (un-propagated): {['D%d'%i for i in unprop]}")

    # --- research-sourced coherence checks (D7) --------------------------------
    # CASCADE-style doc↔register inconsistency: a doc still *applies* a superseded decision.
    superseded_cited = sorted(d for d in cites if d in superseded)
    if superseded_cited:
        issues.append("docs cite SUPERSEDED decision(s) — repoint to the successor or remove: "
                      + "; ".join(f"D{d} in {', '.join(cites[d])}" for d in superseded_cited))
    # Design-rationale completeness: every active decision must carry a real 'why', not a stub.
    rows = parse_rows()
    no_rationale = sorted(i for i in active if not _has_rationale(rows.get(i, {}).get("rationale", "")))
    if no_rationale:
        issues.append("active decision(s) with empty/placeholder rationale (record the *why*): "
                      + ", ".join(f"D{i}" for i in no_rationale))
    return issues, {"active": active, "superseded": superseded, "cites": cites}


def cmd_check() -> int:
    issues, ctx = _coherence_issues()
    active, superseded, cites = ctx["active"], ctx["superseded"], ctx["cites"]

    # Technical-debt visibility: surface accepted coverage gaps (latent governance debt) every audit.
    debt = len(_baseline_set())
    debt_note = f"; {debt} accepted governance-debt gap(s) in baseline" if debt else ""
    print(f"register: {len(active)} active, {len(superseded)} superseded; "
          f"docs cite {len(cites)} distinct D#{debt_note}")
    if issues:
        print("ISSUES:")
        for i in issues:
            print("  - " + i)
        return 1
    print("OK — coherent: IDs sequential, GLANCE matches, all active decisions propagated, "
          "no dangling/superseded cites, rationale present.")
    return 0


def cmd_list() -> int:
    cites = scan_citations()
    for i, label in parse_glance():
        print(f"D{i:<3} {label:<34} cited in {len(cites.get(i, []))} doc(s)")
    return 0


def cmd_next() -> int:
    active, superseded = parse_sections()
    print(f"D{(max(active | superseded) + 1) if (active or superseded) else 1}")
    return 0


# --- targeted propagation (coverage) ---------------------------------------
TOKEN_RESOLVERS = [
    (re.compile(r"SPEC_0(\d)"),            lambda m: f"design/build/SPEC_0{m.group(1)}_*.md"),
    (re.compile(r"design/0(\d)"),          lambda m: f"design/0{m.group(1)}_*.md"),
    (re.compile(r"\bINDEX\b"),             lambda m: "design/INDEX.md"),
    (re.compile(r"OPEN_DESIGN"),           lambda m: "design/OPEN_DESIGN.md"),
    (re.compile(r"ROUTINE_design_build_test"), lambda m: "design/ROUTINE_design_build_test.md"),
    (re.compile(r"ROUTINE_add_decision"),  lambda m: "design/ROUTINE_add_decision.md"),
    (re.compile(r"ROUTINE_coherence_audit"), lambda m: "design/ROUTINE_coherence_audit.md"),
    (re.compile(r"project\.md"),           lambda m: "agent/project.md"),
    (re.compile(r"session\.md"),           lambda m: "agent/session.md"),
]


def parse_rows_targets() -> dict[int, str]:
    """D# -> its 'Propagated to' cell (the last table column), Active section only."""
    out, bucket = {}, False
    for line in _read(DECISIONS).splitlines():
        low = line.lower()
        if low.startswith("## active decisions"): bucket = True; continue
        if low.startswith("## "): bucket = False; continue
        m = ROW_ID_RE.match(line)
        if m and bucket:
            cells = [c.strip() for c in line.split("|")]
            out[int(m.group(1))] = cells[-2] if len(cells) >= 2 else ""
    return out


def _resolve(cell: str) -> set[Path]:
    files: set[Path] = set()
    for rx, tmpl in TOKEN_RESOLVERS:
        for m in rx.finditer(cell):
            files.update((ROOT).glob(tmpl(m)))
    return {f for f in files if f.is_file()}


BASELINE = ROOT / "scripts" / ".coverage_baseline"   # accepted legacy gaps (pre-citation-discipline)


def _current_gaps() -> set[str]:
    """Set of 'D#:relpath' where a declared target doc does not literally cite the D#."""
    gaps = set()
    for nid, cell in parse_rows_targets().items():
        for f in _resolve(cell):
            if not re.search(rf"\bD{nid}\b", _read(f)):
                gaps.add(f"D{nid}:{str(f.relative_to(ROOT)).replace(chr(92), '/')}")
    return gaps


def cmd_coverage() -> int:
    """Lint-style: report only gaps NOT in the accepted baseline. --update-baseline accepts current."""
    current = _current_gaps()
    if "--update-baseline" in sys.argv:
        BASELINE.write_text("\n".join(sorted(current)) + "\n", encoding="utf-8")
        print(f"baseline updated: {len(current)} accepted gap(s) in {BASELINE.name}")
        return 0
    baseline = set(BASELINE.read_text(encoding="utf-8").split()) if BASELINE.is_file() else set()
    new = sorted(current - baseline)
    resolved = sorted(baseline - current)
    for g in new:
        print(f"NEW propagation gap: {g} — declared target doesn't cite it")
    if resolved:
        print(f"note: {len(resolved)} baselined gap(s) now resolved — run `coverage --update-baseline` to prune")
    print(f"coverage: {len(new)} new gap(s); {len(current)} total ({len(current)-len(new)} baselined)"
          + ("" if new else " — clean."))
    return 1 if new else 0


# --- scaffold a new decision (new) -----------------------------------------
def parse_prop_map() -> dict[str, str]:
    out, bucket = {}, False
    for line in _read(DECISIONS).splitlines():
        if line.lower().startswith("## propagation map"): bucket = True; continue
        if line.startswith("## ") and bucket: break
        if bucket and line.startswith("|"):
            m = re.search(r"\*\*([A-Za-z/ -]+)\*\*", line)
            if m:
                cells = [c.strip() for c in line.split("|")]
                out[m.group(1).strip()] = cells[-2] if len(cells) >= 2 else ""
    return out


def cmd_new() -> int:
    from datetime import date
    args = [a for a in sys.argv[2:] if a != "--dry"]
    dry = "--dry" in sys.argv
    if not args:
        print('usage: new "<short label>" [CATEGORY] [--dry]'); return 2
    label = args[0]
    category = args[1] if len(args) > 1 else "SUBSYSTEM"
    active, superseded = parse_sections()
    nid = (max(active | superseded) + 1) if (active or superseded) else 1
    today = date.today().strftime("%m-%d")
    glance_line = f"D{nid}={label}\n"
    row = (f"| D{nid} | {today} | {category} | **{label.capitalize()}:** <STATEMENT — fill in> "
           f"| <rationale doc> | <propagated to> |\n")
    targets = parse_prop_map().get(category, "(see Propagation map)")

    if dry:
        print(f"[dry] would add to GLANCE: {glance_line.strip()}")
        print(f"[dry] would add row:\n{row.strip()}")
    else:
        text = _read(DECISIONS)
        gm = GLANCE_RE.search(text)
        close = text.rfind("-->", gm.start(), gm.end())
        text = text[:close] + glance_line + text[close:]
        lines = text.splitlines(keepends=True)
        si = next(i for i, l in enumerate(lines) if l.startswith("## Superseded"))
        j = si - 1
        # scan back to the last *numbered* row (ROW_ID_RE needs digits, so the example | D<n> | is skipped)
        while j >= 0 and not ROW_ID_RE.match(lines[j]): j -= 1
        lines.insert(j + 1, row)
        DECISIONS.write_text("".join(lines), encoding="utf-8")
        print(f"added D{nid} ({category}) to register + GLANCE.")

    print(f"\nD{nid} — next steps (cite D{nid} in each):")
    print(f"  propagate to: {targets}")
    print(f"  then: fill the row statement → edit targets (one batched message) → "
          f"decision_tools.py sync → check → coverage → note in session.md")
    return 0


# --- scope: resolve the working set (smart context feed, D3) ----------------
def _all_docs() -> list[Path]:
    """design/ + agent/ markdown (excludes the register + the pin file). Used by stats docs_count."""
    out: list[Path] = []
    for d in SCAN_DIRS:
        out += [p for p in d.rglob("*.md")
                if p.resolve() not in (DECISIONS.resolve(), WORKING_SET.resolve())]
    return out


def _scope_docs() -> list[Path]:
    """The doc universe `scope` searches: design/+agent/ plus the root rationale tier (ROOT_DOCS)."""
    return [p for p in ROOT_DOCS if p.is_file()] + _all_docs()


def _scope_cite_map() -> dict[int, list[str]]:
    """scan_citations() extended with ROOT_DOCS — scope-only, so check/coverage stay design/+agent/."""
    cites = {k: set(v) for k, v in scan_citations().items()}
    for p in ROOT_DOCS:
        if p.is_file():
            for n in {int(x) for x in CITE_RE.findall(_read(p))}:
                cites.setdefault(n, set()).add(p.name)
    return {k: sorted(v) for k, v in cites.items()}


def _doc_first_line(p: Path) -> str:
    for line in _read(p).splitlines():
        s = line.strip().lstrip("#").strip()
        if s:
            return s
    return ""


def _heading_for_cite(p: Path, nid: int) -> str:
    """Nearest preceding ##/### heading to the first 'D<nid>' mention in p ('' if none)."""
    heading, pat = "", re.compile(rf"\bD{nid}\b")
    for line in _read(p).splitlines():
        if line.startswith("#"):
            heading = line.strip()
        if pat.search(line):
            return heading
    return ""


def _read_pins() -> list[str]:
    if not WORKING_SET.is_file():
        return []
    return [m.group(1) for m in (re.match(r"\s*-\s+(\S+)", ln) for ln in _read(WORKING_SET).splitlines()) if m]


def _write_pins(selectors: list[str]) -> None:
    body = ("# Working set (session scope)\n"
            "_Pinned selectors the design→build→test loop operates on (D3/D5). "
            "`decision_tools.py scope` resolves these into a read-plan; overwrite per session._\n\n"
            + "\n".join(f"- {s}" for s in selectors) + "\n")
    WORKING_SET.write_text(body, encoding="utf-8")


def _resolve_selectors(selectors: list[str], rows: dict[int, dict]) -> tuple[set[int], set[Path]]:
    """Seed set: each selector -> some decisions and/or some docs."""
    seed_d: set[int] = set()
    seed_docs: set[Path] = set()
    docs = _scope_docs()
    for sel in selectors:
        s = sel.strip()
        if re.fullmatch(r"[Dd]\d+", s):
            nid = int(s[1:])
            if nid in rows: seed_d.add(nid)
        elif re.fullmatch(r"[PpGg]\d+", s) and OPEN_DESIGN.is_file():
            tag = s.upper()
            for line in _read(OPEN_DESIGN).splitlines():
                if re.search(rf"\b{tag}\b", line):
                    seed_d |= {int(n) for n in CITE_RE.findall(line) if int(n) in rows}
                    seed_docs.add(OPEN_DESIGN)
        else:
            hit_docs = [p for p in docs if s.lower() in p.name.lower()]
            if hit_docs:
                seed_docs.update(hit_docs)
            else:                                   # bare keyword: match statements + doc titles
                kw = s.lower()
                seed_d |= {n for n, r in rows.items()
                           if kw in r["statement"].lower() or kw in r["cat"].lower()}
                seed_docs.update(p for p in docs
                                 if kw in p.name.lower() or kw in _doc_first_line(p).lower())
    return seed_d, seed_docs


def cmd_scope() -> int:
    args = [a for a in sys.argv[2:] if not a.startswith("--")]
    files_only, pin = "--files" in sys.argv, "--pin" in sys.argv
    if not args:
        args = _read_pins()
        if not args:
            print("usage: scope <D#|P#|G#|path|keyword> ... [--pin] [--files]")
            print("(no selectors given and no pins in agent/working_set.md)")
            return 2

    rows = parse_rows()
    cites = _scope_cite_map()             # D# -> [doc rel paths citing it] (incl. root rationale tier)
    targets = parse_rows_targets()        # D# -> declared 'Propagated to' cell
    seed_d, seed_docs = _resolve_selectors(args, rows)

    in_play: set[int] = set(seed_d)
    docset: set[str] = set()
    for p in seed_docs:
        docset.add(str(p.relative_to(ROOT)).replace("\\", "/"))
        in_play |= {n for n in (int(x) for x in CITE_RE.findall(_read(p))) if n in rows}
    for nid in in_play:                   # one hop: docs that carry each in-play decision
        docset.update(cites.get(nid, []))

    if files_only:
        for rel in sorted(docset):
            print(rel)
        if pin: _write_pins(args)
        return 0

    print(f"WORKING SET  ({len(in_play)} decision(s), {len(docset)} doc(s))  selectors: {' '.join(args)}")
    print("\nDecisions in play (statements inline — no need to open the register):")
    for nid in sorted(in_play):
        print(f"  D{nid}: {rows[nid]['statement']}")
        if targets.get(nid):
            print(f"        declared targets: {targets[nid]}")
    if not in_play:
        print("  (none — selector matched docs only)")
    print("\nRead (scoped — open these, jump to the heading; don't dump whole files):")
    for rel in sorted(docset):
        carried = sorted(n for n in in_play if rel in cites.get(n, []))
        tag = ("  carries " + ", ".join(f"D{n}" for n in carried)) if carried else ""
        head = _heading_for_cite(ROOT / rel, carried[0]) if carried else ""
        print(f"  {rel}{tag}" + (f"  → {head}" if head else ""))
    if not docset:
        print("  (none)")
    if OPEN_DESIGN.is_file() and in_play:                  # related open items
        items = {m.group(1) for line in _read(OPEN_DESIGN).splitlines()
                 if any(re.search(rf"\bD{n}\b", line) for n in in_play)
                 for m in [re.search(r"\b([PG]\d+)\b", line)] if m}
        if items:
            print("\nOpen items touching these:", ", ".join(sorted(items)))
    print("\nGate: after edits run  decision_tools.py sync → check → coverage")
    if pin:
        _write_pins(args)
        print(f"pinned {len(args)} selector(s) to {WORKING_SET.relative_to(ROOT)}")
    return 0


# --- stats: autotracking signals -> governance_metrics.csv (D4 / ROADMAP) ---
METRICS_HEADER = ["ts", "decisions_active", "decisions_superseded", "superseded_rate",
                  "coverage_total", "coverage_baselined", "coverage_new",
                  "avg_propagation_breadth", "propagation_breadth_spread", "glance_max_len",
                  "orphans", "docs_count", "days_since_last_decision"]


def _orphan_count() -> int:
    man = _read(DOCS_MANIFEST)
    skip = {"INDEX.md", "DECISIONS.md", "ROUTINE_add_decision.md", "OPEN_DESIGN.md"}
    cand = list((ROOT / "design").glob("*.md")) + list((ROOT / "design" / "build").glob("*.md"))
    return len([p for p in cand if p.name not in skip and p.name not in man])


def _breadths(active: set[int]) -> list[int]:
    """Declared-target count per active decision (the propagation breadth)."""
    targets = parse_rows_targets()
    return [len([t for t in re.split(r"[·,]", targets.get(n, "")) if t.strip()]) for n in active]


def _days_since_last_decision(rows: dict) -> int:
    """Days since the most recent dated decision (register row date, MM-DD); -1 if none dated."""
    from datetime import date
    today = date.today()
    best = None
    for r in rows.values():
        m = re.fullmatch(r"(\d{2})-(\d{2})", r.get("date", "").strip())
        if not m:
            continue
        try:
            cand = date(today.year, int(m.group(1)), int(m.group(2)))
        except ValueError:
            continue
        if cand <= today and (best is None or cand > best):
            best = cand
    return (today - best).days if best else -1


def cmd_stats() -> int:
    import csv
    from datetime import datetime, timezone
    active, superseded = parse_sections()
    glance, current = parse_glance(), _current_gaps()
    baseline = set(BASELINE.read_text(encoding="utf-8").split()) if BASELINE.is_file() else set()
    breadths = _breadths(active)
    total = len(active) + len(superseded)
    row = {"ts": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
           "decisions_active": len(active), "decisions_superseded": len(superseded),
           "superseded_rate": round(len(superseded) / max(total, 1), 3),
           "coverage_total": len(current), "coverage_baselined": len(current & baseline),
           "coverage_new": len(current - baseline),
           "avg_propagation_breadth": round(sum(breadths) / len(breadths), 2) if breadths else 0.0,
           "propagation_breadth_spread": (max(breadths) - min(breadths)) if breadths else 0,
           "glance_max_len": max((len(lbl) for _, lbl in glance), default=0),
           "orphans": _orphan_count(), "docs_count": len(_all_docs()),
           "days_since_last_decision": _days_since_last_decision(parse_rows())}

    prev = None
    if METRICS_CSV.is_file():
        existing = list(csv.DictReader(METRICS_CSV.open(encoding="utf-8")))
        prev = existing[-1] if existing else None
    new_file = not METRICS_CSV.is_file()
    with METRICS_CSV.open("a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=METRICS_HEADER)
        if new_file: w.writeheader()
        w.writerow(row)
    if "--csv-only" in sys.argv:
        print(f"appended metrics row to {METRICS_CSV.name}"); return 0

    print(f"governance metrics @ {row['ts']}  (-> {METRICS_CSV.name})")
    for k in METRICS_HEADER[1:]:
        delta = ""
        if prev and prev.get(k) not in (None, ""):
            try:
                d = float(row[k]) - float(prev[k])
                if d: delta = f"  ({'+' if d > 0 else ''}{round(d, 3)})"
            except ValueError:
                pass
        print(f"  {k:<26} {row[k]}{delta}")
    flags = []
    if row["coverage_new"]:
        flags.append(f"{row['coverage_new']} NEW coverage gap(s) — run `coverage`")
    if row["glance_max_len"] > 34:
        flags.append(f"glance label {row['glance_max_len']} chars (>34) — trim (see `tune`)")
    for fl in flags:
        print("  ! " + fl)
    return 0


# --- propagate: script the cited-stub edits into a decision's declared targets (D4, SPEC_01 M3) ---
LABEL_RE = re.compile(r"\*\*(.+?):\*\*")


def _decision_label(nid: int, rows: dict) -> str:
    m = LABEL_RE.search(rows.get(nid, {}).get("statement", ""))
    return m.group(1) if m else ""


def _targets_missing_cite(nid: int) -> list[Path]:
    """Declared-target files for D<nid> that don't yet literally cite it (the coverage gaps)."""
    cell = parse_rows_targets().get(nid, "")
    return sorted((f for f in _resolve(cell) if not re.search(rf"\bD{nid}\b", _read(f))), key=str)


def cmd_propagate() -> int:
    """propagate <D#> [--apply] — insert a cited stub into each declared target missing the cite."""
    args = [a for a in sys.argv[2:] if not a.startswith("--")]
    apply = "--apply" in sys.argv
    if not args or not re.fullmatch(r"[Dd]?\d+", args[0]):
        print("usage: propagate <D#> [--apply]"); return 2
    nid = int(re.sub(r"\D", "", args[0]))
    rows = parse_rows()
    if nid not in rows:
        print(f"! D{nid} is not in the active register"); return 2
    if not parse_rows_targets().get(nid, "").strip():
        print(f"D{nid} has no declared targets (the 'Propagated to' cell is empty) — nothing to do."); return 0
    missing = _targets_missing_cite(nid)
    if not missing:
        print(f"D{nid}: all declared targets already cite it — coverage is clean, nothing to do."); return 0
    label = _decision_label(nid, rows)
    stub = f"<applies D{nid} — {label}: state how this doc uses D{nid}, then remove the brackets>"
    print(f"D{nid} — {len(missing)} declared target(s) missing the cite:")
    for f in missing:
        rel = str(f.relative_to(ROOT)).replace("\\", "/")
        print(f"  {'+ insert into' if apply else 'would insert into'} {rel}")
        print(f"      {stub}")
        if apply:
            f.write_text(_read(f).rstrip("\n") + "\n\n" + stub + "\n", encoding="utf-8")
    tail = ("inserted — now fill each stub's text, then sync → check → coverage."
            if apply else "(dry-run) re-run with --apply to insert, then fill the stubs.")
    print(f"\n{tail}")
    return 0


# --- tune: metrics + state -> ranked config-knob actions; --apply does mechanical knobs (D4, M4) ---
GLANCE_BUDGET = 34


def _baseline_set() -> set[str]:
    return set(BASELINE.read_text(encoding="utf-8").split()) if BASELINE.is_file() else set()


def _prune_baseline() -> str | None:
    baseline = _baseline_set()
    keep = baseline & _current_gaps()
    if keep == baseline:
        return None
    BASELINE.write_text(("\n".join(sorted(keep)) + "\n") if keep else "", encoding="utf-8")
    return f"pruned {len(baseline) - len(keep)} resolved gap(s) from {BASELINE.name}"


def _tune_findings() -> list[tuple]:
    """Severity-ranked signal→knob findings from current state + metrics history (unsorted).
    Each tuple = (severity, signal, observed, knob, mechanical-callable|None). Shared by tune + audit."""
    import csv
    active, superseded = parse_sections()
    glance, current, baseline = parse_glance(), _current_gaps(), _baseline_set()
    total = len(active) + len(superseded)
    findings = []   # (severity, signal, observed, knob, mechanical-callable|None)

    if baseline - current:
        findings.append((2, "baseline drift", f"{len(baseline - current)} baselined gap(s) now resolved",
                         "prune .coverage_baseline", _prune_baseline))
    for i, l in glance:
        if len(l) > GLANCE_BUDGET:
            findings.append((1, "glance label too long", f"D{i} label {len(l)}>{GLANCE_BUDGET} chars: '{l}'",
                             f"shorten D{i}'s GLANCE label by hand — lossy reword, not auto-applied", None))
    new = current - baseline
    if new:
        ids = sorted({g.split(":")[0] for g in new})
        findings.append((3, "open coverage gaps", f"{len(new)} new: {', '.join(sorted(new))}",
                         f"run `propagate {ids[0]}` (or cite by hand)", None))
    if total and len(superseded) / total > 0.3:
        findings.append((2, "high superseded rate", f"{len(superseded)}/{total} decisions superseded",
                         "deciding too early — revisit stage timing (METHODOLOGY)", None))
    breadths = _breadths(active)
    if breadths and (max(breadths) - min(breadths)) >= 3:
        findings.append((1, "uneven propagation breadth",
                         f"declared targets range {min(breadths)}-{max(breadths)} across {len(breadths)} decisions",
                         "propagation map may be too generic — split a category / tighten its targets", None))
    orph = _orphan_count()
    if orph:
        findings.append((2, "manifest orphans", f"{orph} doc(s) on disk not in docs_manifest.txt",
                         "add them to docs_manifest.txt", None))
    if METRICS_CSV.is_file():
        r = list(csv.DictReader(METRICS_CSV.open(encoding="utf-8")))
        cn = [int(x["coverage_new"]) for x in r if x.get("coverage_new", "").isdigit()]
        if len(cn) >= 3 and cn[-1] > cn[0] and cn[-1] > 0:
            findings.append((2, "coverage_new trending up", f"{cn[0]}->{cn[-1]} over {len(cn)} runs",
                             "tighten citation discipline / propagation map", None))
    return findings


def cmd_tune() -> int:
    """tune [--apply] — rank signal->knob actions from metrics + state; --apply runs mechanical ones."""
    apply = "--apply" in sys.argv
    findings = _tune_findings()
    if not findings:
        print("tune: no actionable signals — governance is clean."); return 0
    findings.sort(key=lambda x: -x[0])
    mech = [(sig, fn) for sev, sig, obs, knob, fn in findings if fn]
    print(f"tune — {len(findings)} finding(s) (severity-ranked):")
    for sev, sig, obs, knob, fn in findings:
        print(f"  ({sev}) {sig} {'[mechanical]' if fn else '[judgment]'}")
        print(f"        observed: {obs}")
        print(f"        knob: {knob}")
    if not apply:
        if mech:
            print(f"\n{len(mech)} mechanical knob(s) auto-appliable: re-run `tune --apply`.")
        print("(judgment knobs are proposals — act on them by hand.)")
        return 0
    print("\napplying mechanical knobs:")
    done = 0
    for sig, fn in mech:
        res = fn()
        if res:
            print("  ok " + res); done += 1
        else:
            print(f"  - {sig}: already applied")
    print(f"\napplied {done} knob(s)." + (" Now run sync -> check -> coverage." if done else ""))
    return 0


# --- audit: the periodic high-effort whole-tree coherence + realignment pass (D9) ----------------
# Steps back from the per-loop gate to sweep the WHOLE tree: full coherence + baseline-unfiltered
# coverage debt + goal-alignment (D# <-> O#) + drift/conformance (per-decision content hash, the D8
# slice). Emits one severity-ranked remediation worklist; propose-first (D4): mechanical fixes on
# --apply, conformance re-stamp on --update-hashes.

def parse_goals() -> dict[int, str]:
    """O# -> goal text from project.md's '## Goals' section. Empty dict if the section is absent or
    only carries <placeholder> stubs — so a fresh template stays quiet until real goals are added."""
    if not PROJECT_MD.is_file():
        return {}
    out, bucket = {}, False
    for line in _read(PROJECT_MD).splitlines():
        if line.strip().lower().startswith("## goals"):
            bucket = True; continue
        if line.startswith("## ") and bucket:
            break
        if bucket:
            m = re.match(r"\s*[-*]\s*\*{0,2}O(\d+)\b\*{0,2}[.):]?\s*(.*)", line)
            if m and m.group(2).strip() and not PLACEHOLDER_RE.match(m.group(2).strip()):
                out[int(m.group(1))] = m.group(2).strip()
    return out


def _decision_goal_map() -> dict[int, set[int]]:
    """Active D# -> set of O# goal-ids its register row references (the goal→decision alignment links)."""
    out, bucket = {}, False
    for line in _read(DECISIONS).splitlines():
        low = line.lower()
        if low.startswith("## active decisions"): bucket = True; continue
        if low.startswith("## ") and bucket: break
        m = ROW_ID_RE.match(line)
        if m and bucket:
            out[int(m.group(1))] = {int(x) for x in GOAL_ID_RE.findall(line)}
    return out


def _alignment_findings(active: set[int]) -> list[tuple]:
    """Goal-alignment (traceability re-validation): orphan decisions / unaddressed goals / dangling refs.
    Returns one info finding if no goals are declared (the template's natural pre-objectives state)."""
    goals = parse_goals()
    gmap = _decision_goal_map()
    if not goals:
        return [(1, "no goals declared", "project.md has no '## Goals' (O#) section with real goals",
                 "add O# goals to project.md + reference them in decisions to enable alignment tracking", None)]
    referenced = set().union(*gmap.values()) if gmap else set()
    findings = []
    dangling = sorted({o for s in gmap.values() for o in s} - set(goals))
    if dangling:
        findings.append((3, "dangling goal ref", f"decision(s) cite undefined goal(s): {['O%d'%o for o in dangling]}",
                         "fix the O# typo or define the goal in project.md '## Goals'", None))
    orphan_d = sorted(n for n in active if not gmap.get(n))
    if orphan_d:
        findings.append((2, "decision advances no goal",
                         f"{['D%d'%n for n in orphan_d]} reference no O# goal (scope-creep / unanchored-work check)",
                         "link each to the goal it serves (add its O# to the row) or retire the decision", None))
    orphan_g = sorted(o for o in goals if o not in referenced)
    if orphan_g:
        findings.append((2, "goal has no decision",
                         f"{['O%d'%o for o in orphan_g]} advanced by no active decision (unaddressed objective)",
                         "decide how to address it (record a D# referencing the O#) or drop the goal", None))
    return findings


def _decision_hash(row: dict) -> str:
    """Stable 12-char content hash of a decision's canonical content (statement + rationale + targets)."""
    blob = "\x1f".join((row.get("statement", ""), row.get("rationale", ""), row.get("targets", "")))
    return hashlib.sha1(blob.encode("utf-8")).hexdigest()[:12]


def _load_decision_hashes() -> dict[int, str]:
    """Read the conformance baseline (`.decision_hashes`): D# -> last-stamped content hash."""
    if not DECISION_HASHES.is_file():
        return {}
    out = {}
    for tok in DECISION_HASHES.read_text(encoding="utf-8").split():
        if ":" in tok:
            k, v = tok.split(":", 1)
            if k[1:].isdigit():
                out[int(k[1:])] = v
    return out


def _save_decision_hashes(hashes: dict[int, str]) -> None:
    DECISION_HASHES.write_text("\n".join(f"D{k}:{v}" for k, v in sorted(hashes.items())) + "\n",
                               encoding="utf-8")


def _drift_findings(active: set[int], rows: dict, cites: dict) -> tuple[list[tuple], dict[int, str], int]:
    """Citation-staleness (D8 conformance slice): a decision whose content hash changed since the last
    stamp → its citing docs may no longer honor it (re-review). Returns (findings, current_hashes, unstamped)."""
    stored = _load_decision_hashes()
    current = {n: _decision_hash(rows[n]) for n in active if n in rows}
    findings = []
    for n in sorted(active):
        if n in stored and n in current and stored[n] != current[n]:
            citing = cites.get(n, [])
            obs = (f"D{n}'s statement/rationale/targets changed since the last conformance stamp; "
                   + (f"re-review {len(citing)} citing doc(s): {', '.join(citing)}" if citing
                      else "no docs cite it yet"))
            findings.append((2, "stale citation (drift)", obs,
                             f"re-verify each citing doc still honors D{n}, then `audit --update-hashes`", None))
    unstamped = len([n for n in current if n not in stored])
    return findings, current, unstamped


def cmd_audit() -> int:
    """audit [--apply] [--update-hashes] — periodic, high-effort, whole-tree coherence + realignment
    pass (D9): coherence + baseline-unfiltered coverage debt + goal-alignment + drift, as one
    severity-ranked worklist. Propose-first: --apply runs the lossless mechanical fixes;
    --update-hashes re-stamps the D8 conformance baseline (clears drift flags — an explicit re-review act)."""
    apply = "--apply" in sys.argv
    update_hashes = "--update-hashes" in sys.argv
    active, superseded = parse_sections()
    rows = parse_rows()
    cites = scan_citations()
    current_gaps = _current_gaps()
    baseline = _baseline_set()
    goals = parse_goals()

    drift, cur_hashes, unstamped = _drift_findings(active, rows, cites)

    if update_hashes:                                  # explicit re-review act → re-stamp + exit
        _save_decision_hashes(cur_hashes)
        print(f"conformance baseline stamped: {len(cur_hashes)} decision hash(es) -> {DECISION_HASHES.name}")
        return 0

    findings: list[tuple] = []
    coh_issues, _ = _coherence_issues()
    findings += [(3, "coherence break", iss, "fix per `check` (run it for the full detail)", None)
                 for iss in coh_issues]
    findings += _alignment_findings(active)
    findings += drift
    # coverage as debt: surface ALL gaps, including accepted-baseline ones (debt visibility)
    new_gaps = sorted(current_gaps - baseline)
    based_gaps = sorted(current_gaps & baseline)
    if new_gaps:
        nid = new_gaps[0].split(":")[0]
        findings.append((3, "open coverage gap",
                         f"{len(new_gaps)} declared target(s) don't cite their D#: {', '.join(new_gaps)}",
                         f"run `propagate {nid}` (or cite by hand)", None))
    if based_gaps:
        findings.append((1, "accepted governance debt",
                         f"{len(based_gaps)} baselined gap(s) (latent debt): {', '.join(based_gaps)}",
                         "schedule paydown; prune any now-resolved with `audit --apply`", _prune_baseline))
    findings += [f for f in _tune_findings()             # debt/churn signals; skip ones already folded in above
                 if f[1] not in {"open coverage gaps", "baseline drift"}]

    print("=" * 72)
    print("AUDIT — periodic coherence + realignment (D9)")
    print(f"register: {len(active)} active, {len(superseded)} superseded · "
          f"coverage gaps: {len(current_gaps)} ({len(based_gaps)} baselined) · "
          f"goals: {len(goals)} · unstamped decisions: {unstamped}")
    print("=" * 72)

    if not findings:
        print("CLEAN — no coherence, alignment, drift, or debt findings.")
        if unstamped:
            print(f"note: {unstamped} decision(s) not yet conformance-stamped — "
                  f"run `audit --update-hashes` to set the drift baseline.")
        return 0

    findings.sort(key=lambda x: -x[0])
    mech = [(sig, fn) for sev, sig, obs, knob, fn in findings if fn]
    print(f"{len(findings)} finding(s), severity-ranked (3=high):")
    for sev, sig, obs, knob, fn in findings:
        print(f"  ({sev}) {sig} {'[mechanical]' if fn else '[judgment]'}")
        print(f"        observed: {obs}")
        print(f"        action:   {knob}")
    if unstamped:
        print(f"\n  note: {unstamped} decision(s) not yet conformance-stamped — "
              f"run `audit --update-hashes` to set the drift baseline.")
    if not apply:
        if mech:
            print(f"\n{len(mech)} mechanical fix(es) auto-appliable: re-run `audit --apply`.")
        print("(judgment findings are proposals — act on them, then re-run `audit`.)")
        return 1
    print("\napplying mechanical fixes:")
    done = 0
    for sig, fn in mech:
        res = fn()
        if res:
            print("  ok " + res); done += 1
        else:
            print(f"  - {sig}: already applied")
    print(f"\napplied {done} fix(es)." + (" Now run sync -> check -> coverage." if done else ""))
    return 1


def main() -> int:
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    return {"check": cmd_check, "sync": cmd_sync, "list": cmd_list, "next": cmd_next,
            "coverage": cmd_coverage, "new": cmd_new, "docs": cmd_docs,
            "scope": cmd_scope, "stats": cmd_stats, "propagate": cmd_propagate, "tune": cmd_tune,
            "audit": cmd_audit}.get(
        cmd, lambda: (print(f"unknown command: {cmd}") or 2)
    )()


if __name__ == "__main__":
    sys.exit(main())
